buy-pattern: '^\D+(?=\d)|(?<=\d)\D+(?=\d)|(?=\D$)'
protect-explode: true
material-pattern: \[(.+)\]
auto-fill-name: true
server-shop: '[Server]'
protect-chest-access: true
protect-break: true
log-block: false
sell-pattern: '^\D+(?=\d)|(?<=\d)\D+(?=\d)|(?=\D$)'
language: English
protect-existing-chest: true
trigger-redstone: false
extended-names: false
