name: PhysicalShop
main: com.wolvereness.physicalshop.PhysicalShop
version: 8.4.2
url: http://dev.bukkit.org/server-mods/physicalshop/
commands:
   physicalshop:
      description: Reloads the configuration
authors:
    - Wolvereness